user_login:
    path: /
    controller: DatingLibre\AppBundle\Controller\UserLoginController::login

user_register:
    path: /register
    controller: DatingLibre\AppBundle\Controller\UserRegisterController::register
    methods: GET|POST

user_password_update:
    path: /user/password/update
    controller: DatingLibre\AppBundle\Controller\UserPasswordUpdateController::processPasswordReset
    methods: GET|POST

user_password_reset:
    path: /user/password/reset
    controller: DatingLibre\AppBundle\Controller\UserPasswordResetController::password
    methods: GET|POST

user_block:
    path: /block/{userId}
    controller: DatingLibre\AppBundle\Controller\UserBlockController::block
    methods: GET|POST

user_matches_index:
    path: /matches
    controller: DatingLibre\AppBundle\Controller\UserMatchesIndexController::index
    methods: GET
 
user_send_message:
    path: /message/{userId}
    controller: DatingLibre\AppBundle\Controller\UserSendMessageController::message
    methods: GET|POST
 
moderator_profile_images:
    path: /moderator/profile/images
    controller: DatingLibre\AppBundle\Controller\ModeratorImageController::index
    methods: GET|POST
 
user_account_delete:
    path: /account/delete
    controller: DatingLibre\AppBundle\Controller\UserAccountDeleteController::delete
    methods: GET|POST
 
user_profile_edit:
    path: /profile/edit
    controller: DatingLibre\AppBundle\Controller\UserProfileEditController::edit
    methods: GET|POST
 
user_profile_image:
    path: /profile/image
    controller: DatingLibre\AppBundle\Controller\UserProfileImageController::index
    methods: GET|POST
 
user_profile_index:
    path: /profile
    controller: DatingLibre\AppBundle\Controller\UserProfileIndexController::index
    methods: GET
 
user_country_regions:
    path: /location/country/{countryId}/regions
    controller: DatingLibre\AppBundle\Controller\UserLocationController::displayRegions
    methods: GET
 
user_region_cities:
    path: /location/region/{regionId}/cities
    controller: DatingLibre\AppBundle\Controller\UserLocationController::displayCities
    methods: GET
 
user_search_index:
    path: /search
    controller: DatingLibre\AppBundle\Controller\UserSearchIndexController::index
    methods: GET|POST
 
user_profile_view:
    path: /profile/{userId}/view
    controller: DatingLibre\AppBundle\Controller\UserProfileViewController::index
    methods: GET

user_registration_terms:
    path: /register/terms
    controller: DatingLibre\AppBundle\Controller\UserRegisterController::terms
    methods: GET

user_process_token:
    path: /token/{secret}
    controller: DatingLibre\AppBundle\Controller\UserTokenController::processConfirm
    methods: GET

user_account_subscription:
    path: /account/subscription
    controller: DatingLibre\AppBundle\Controller\UserAccountSubscriptionController::viewSubscription
    methods: GET

user_report:
    path: /report/{userId}
    controller: DatingLibre\AppBundle\Controller\UserReportController::report
    methods: GET|POST

moderator_profile_view:
    path: /moderator/profile/{userId}/view
    controller: DatingLibre\AppBundle\Controller\ModeratorProfileViewController::index
    methods: GET

moderator_profile_reports:
    path: /moderator/profile/{userId}/reports
    controller: DatingLibre\AppBundle\Controller\ModeratorProfileReportsController::index
    methods: GET

moderator_profile_report:
    path: /moderator/profile/{userId}/report/{reportId}
    controller: DatingLibre\AppBundle\Controller\ModeratorProfileReportController::view
    methods: GET|POST

moderator_reports:
    path: /moderator/reports
    controller: DatingLibre\AppBundle\Controller\ModeratorReportsController::index
    methods: GET|POST

moderator_suspensions:
    path: /moderator/suspensions
    controller: DatingLibre\AppBundle\Controller\ModeratorSuspensionsController::index
    methods: GET|POST

moderator_profile_suspensions:
    path: /moderator/profile/{userId}/suspensions
    controller: DatingLibre\AppBundle\Controller\ModeratorProfileSuspensionsController::index
    methods: GET|POST

moderator_profile_enqueue_permanent_suspension:
    path: /moderator/profile/{userId}/suspend
    controller: DatingLibre\AppBundle\Controller\ModeratorProfileEnqueuePermanentSuspension::enqueue
    methods: GET|POST

moderator_profile_suspension:
    path: /moderator/profile/{userId}/suspension/{suspensionId}
    controller: DatingLibre\AppBundle\Controller\ModeratorProfileSuspensionController::view
    methods: GET|POST

admin_profile_permanently_suspend:
    path: /admin/profile/{userId}/suspension
    controller: DatingLibre\AppBundle\Controller\AdminProfilePermanentlySuspendController::view

admin_events_index:
    path: /admin/events
    controller: DatingLibre\AppBundle\Controller\AdminEventsController::index
    methods: GET|POST

admin_permanent_suspension_queue:
    path: /admin/permanentSuspensions
    controller: DatingLibre\AppBundle\Controller\AdminSuspensionQueueController::view
    methods: GET

ccbill_webhook:
    path: /ccbill/webhook
    controller: DatingLibre\AppBundle\Controller\CcBillWebhookController::webhook
    methods: GET|POST