services:
  DatingLibre\AppBundle\Behat\Page\LoginPage:
    arguments:
      - '@behat.mink.default_session'
      - '@behat.mink.parameters'
      - '@router'

  DatingLibre\AppBundle\Behat\Page\RegistrationPage:
    arguments:
      - '@behat.mink.default_session'
      - '@behat.mink.parameters'
      - '@router'

  DatingLibre\AppBundle\Behat\Page\ProfileIndexPage:
    arguments:
      - '@behat.mink.default_session'
      - '@behat.mink.parameters'
      - '@router'

  DatingLibre\AppBundle\Behat\Page\ProfileEditPage:
    arguments:
      - '@behat.mink.default_session'
      - '@behat.mink.parameters'
      - '@router'

  DatingLibre\AppBundle\Behat\Page\ProfileImagePage:
    arguments:
      - '@behat.mink.default_session'
      - '@behat.mink.parameters'
      - '@router'

  DatingLibre\AppBundle\Behat\Page\SearchPage:
    arguments:
      - '@behat.mink.default_session'
      - '@behat.mink.parameters'
      - '@router'
      -
  DatingLibre\AppBundle\Behat\Page\MessageSendPage:
    arguments:
      - '@behat.mink.default_session'
      - '@behat.mink.parameters'
      - '@router'

  DatingLibre\AppBundle\Behat\Page\MatchesPage:
    arguments:
      - '@behat.mink.default_session'
      - '@behat.mink.parameters'
      - '@router'

  DatingLibre\AppBundle\Behat\Page\BlockPage:
    arguments:
      - '@behat.mink.default_session'
      - '@behat.mink.parameters'
      - '@router'

  DatingLibre\AppBundle\Behat\Page\ModerateProfileImagesPage:
    arguments:
      - '@behat.mink.default_session'
      - '@behat.mink.parameters'
      - '@router'

  DatingLibre\AppBundle\Behat\RegistrationContext:
    public: true
    arguments:
      - '@DatingLibre\AppBundle\Behat\Page\RegistrationPage'

  DatingLibre\AppBundle\Behat\SearchContext:
    public: true
    arguments:
      - '@DatingLibre\AppBundle\Service\UserService'
      - '@DatingLibre\AppBundle\Repository\ProfileRepository'
      - '@DatingLibre\AppBundle\Repository\RegionRepository'
      - '@DatingLibre\AppBundle\Behat\Page\SearchPage'
      - '@DatingLibre\AppBundle\Repository\FilterRepository'
      - '@DatingLibre\AppBundle\Service\UserInterestFilterService'
      - '@router'

  DatingLibre\AppBundle\Behat\ProfileEditContext:
    public: true
    arguments:
      - '@DatingLibre\AppBundle\Service\UserService'
      - '@DatingLibre\AppBundle\Repository\UserRepository'
      - '@DatingLibre\AppBundle\Repository\ProfileRepository'
      - '@DatingLibre\AppBundle\Service\UserAttributeService'
      - '@DatingLibre\AppBundle\Service\UserInterestService'
      - '@DatingLibre\AppBundle\Service\RequirementService'
      - '@DatingLibre\AppBundle\Repository\CityRepository'
      - '@DatingLibre\AppBundle\Repository\RegionRepository'
      - '@DatingLibre\AppBundle\Repository\CountryRepository'
      - '@DatingLibre\AppBundle\Behat\Page\ProfileIndexPage'
      - '@DatingLibre\AppBundle\Behat\Page\ProfileEditPage'

  DatingLibre\AppBundle\Behat\ProfileImageContext:
    public: true
    arguments:
      - '@DatingLibre\AppBundle\Behat\Page\ProfileImagePage'
      - '@DatingLibre\AppBundle\Service\ProfileService'
      - '@DatingLibre\AppBundle\Repository\ProfileRepository'
      - '@DatingLibre\AppBundle\Repository\UserRepository'
      - '@DatingLibre\AppBundle\Service\ImageService'

  DatingLibre\AppBundle\Behat\BlockContext:
    public: true
    arguments:
      - '@DatingLibre\AppBundle\Service\UserService'
      - '@DatingLibre\AppBundle\Repository\BlockRepository'
      - '@DatingLibre\AppBundle\Behat\Page\BlockPage'

  DatingLibre\AppBundle\Behat\UserContext:
    public: true
    arguments:
      - '@DatingLibre\AppBundle\Repository\UserRepository'
      - '@DatingLibre\AppBundle\Service\UserService'
      - '@DatingLibre\AppBundle\Behat\Page\LoginPage'

  DatingLibre\AppBundle\Behat\AccountContext:
    public: true
    arguments:
      - '@DatingLibre\AppBundle\Service\UserService'
      - '@DatingLibre\AppBundle\Repository\UserSettingRepository'
      - '@DatingLibre\AppBundle\Service\UserArchiveService'
      - '@DatingLibre\AppBundle\Repository\UserArchiveRepository'

  DatingLibre\AppBundle\Behat\MessageContext:
    public: true
    arguments:
      - '@DatingLibre\AppBundle\Service\UserService'
      - '@DatingLibre\AppBundle\Repository\MessageRepository'
      - '@DatingLibre\AppBundle\Behat\Page\MessageSendPage'
      - '@DatingLibre\AppBundle\Behat\Page\MatchesPage'

  DatingLibre\AppBundle\Behat\ImageContext:
    public: true
    arguments:
      - '@DatingLibre\AppBundle\Service\UserService'
      - '@DatingLibre\AppBundle\Repository\ImageRepository'
      - '@DatingLibre\AppBundle\Service\ImageService'

  DatingLibre\AppBundle\Behat\ModerateContext:
    public: true
    arguments:
      - '@DatingLibre\AppBundle\Service\ImageService'
      - '@DatingLibre\AppBundle\Repository\UserRepository'
      - '@DatingLibre\AppBundle\Behat\Page\ModerateProfileImagesPage'

  DatingLibre\AppBundle\Behat\SubscriptionContext:
    public: true
    arguments:
      - '@DatingLibre\AppBundle\Service\UserService'
      - '@DatingLibre\AppBundle\Repository\SubscriptionRepository'

  DatingLibre\AppBundle\Behat\SuspensionContext:
    public: true
    arguments:
      - '@DatingLibre\AppBundle\Service\UserService'
      - '@DatingLibre\AppBundle\Repository\SuspensionRepository'
      - '@DatingLibre\AppBundle\Service\SuspensionService'

  DatingLibre\AppBundle\Behat\CcBillContext:
    public: true
    arguments:
      - '@DatingLibre\AppBundle\Service\UserService'
      - '@DatingLibre\AppBundle\Repository\EventRepository'
      - '@DatingLibre\AppBundle\Repository\SubscriptionRepository'
      - '@DatingLibre\AppBundle\Service\CcBillEventService'

  DatingLibre\AppBundle\Behat\ReportContext:
    public: true
    arguments:
      - '@DatingLibre\AppBundle\Service\UserService'
      - '@DatingLibre\AppBundle\Repository\ReportRepository'
